app_version: 0.19.0
capabilities:
- description: Celery, Dispatcharr are able to change file ownership arbitrarily
  name: CHOWN
- description: Celery, Dispatcharr are able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Celery, Dispatcharr are able to bypass permission checks for file operations
  name: FOWNER
- description: Celery, Dispatcharr are able to change group ID of processes
  name: SETGID
- description: Celery, Dispatcharr are able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/Dispatcharr/Dispatcharr/releases
date_added: '2026-02-14'
description: Dispatcharr is an open-source powerhouse for managing IPTV streams, EPG
  data, and VOD content with elegance and control.
home: https://github.com/Dispatcharr/Dispatcharr
host_mounts: []
icon: https://media.sys.truenas.net/apps/dispatcharr/icons/icon.svg
keywords:
- iptv
- epg
- vod
- streaming
lib_version: 2.2.0
lib_version_hash: 75344d294d8d9bb68ee52f390d202dc7ec8746c4ef09d1d37e599500609bedaf
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: dispatcharr
run_as_context:
- description: Container [celery] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [dispatcharr] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/Dispatcharr/Dispatcharr
title: Dispatcharr
train: community
version: 1.0.1
